# Permalinks
#
permalink:           pretty

# Setup
title:               nonterminal
tagline:             Notes.
url:                 http://notes.nonterminal.net
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              schulze
  url:               "notes.nonterminal.net"
  email:             ""

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:
  about: '/about'
  archive: '/archive'
  feed: '/atom.xml'

