# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               schulze
tagline:             Zeugs.
url:                 http://schulze.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              schulze
  url:                ""
  email:             ""

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:
  about: '/about'
  archive: '/archive'
  feed: '/atom.xml'

